from bus.Serializers.busSerializer import BusSerializer
from bus.Serializers.choferSerializer import ChoferSerializer
from bus.Serializers.trayectoSerializer import TrayectoSerializer
from bus.Serializers.ReservaPasajeroSerializer import ReservaPasajeroSerializer
from bus.Serializers.PasajeroSerializer import PasajeroSerializer
from bus.Serializers.lugarSerializer import LugarSerializer
from bus.Serializers.estadoSerializer import EstadoSerializer