# Generated by Django 3.1.5 on 2021-01-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('BUS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BUS_MARCA', models.CharField(blank=True, max_length=50, null=True)),
                ('BUS_MODELO', models.CharField(blank=True, max_length=100, null=True)),
                ('BUS_VIGENCIA', models.IntegerField()),
                ('LGR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.lugar')),
            ],
        ),
    ]
