# Generated by Django 3.1.5 on 2021-01-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['BUS_ID'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
    ]
