# Generated by Django 3.1.5 on 2021-01-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20210114_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('CFR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CFR_NOMBRE', models.CharField(blank=True, max_length=100, null=True)),
                ('CFR_APELLIDO', models.CharField(blank=True, max_length=100, null=True)),
                ('CFR_RUT', models.CharField(max_length=100)),
                ('CFR_VIGENCIA', models.IntegerField()),
                ('LGR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.lugar')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['CFR_ID'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('EST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EST_NOMBRE', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['EST_ID'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PRS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PRS_NOMBRE', models.CharField(blank=True, max_length=100, null=True)),
                ('PRS_APELLIDO', models.CharField(blank=True, max_length=100, null=True)),
                ('PRS_RUT', models.CharField(max_length=100)),
                ('PRS_VIGENCIA', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['PRS_ID'],
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('TYO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LGR_ID_INICIO', models.IntegerField()),
                ('LGR_ID_TERMINO', models.IntegerField()),
                ('TYO_VIGENCIA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPasajero',
            fields=[
                ('RSV_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FDT_DIA_INICIO', models.DateTimeField()),
                ('FDT_HORA_INICIO', models.TimeField()),
                ('FDT_DIA_LLEGADA', models.DateTimeField()),
                ('FDT_HORA_LLEGADA', models.TimeField()),
                ('RSV_VIGENCIA', models.IntegerField()),
                ('BUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('CFR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.chofer')),
                ('EST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.estado')),
                ('TYO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.trayecto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['RSV_ID'],
            },
        ),
        migrations.CreateModel(
            name='PromedioTrayectosReservas',
            fields=[
                ('PTR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('N_PASAJEROS', models.IntegerField()),
                ('N_LARGO', models.IntegerField()),
                ('PTR_VIGENCIA', models.IntegerField()),
                ('TYO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.trayecto')),
            ],
            options={
                'verbose_name': 'Trayecto',
                'verbose_name_plural': 'Trayectos',
                'ordering': ['PTR_ID'],
            },
        ),
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('PSR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PSR_N_RESERVA', models.IntegerField()),
                ('PSR_VIGENCIA', models.IntegerField()),
                ('PRS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.persona')),
                ('VJE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.reservapasajero')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['PSR_ID'],
            },
        ),
    ]
