# Generated by Django 3.1.5 on 2021-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20210114_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservapasajero',
            name='FDT_HORA_INICIO',
        ),
        migrations.RemoveField(
            model_name='reservapasajero',
            name='FDT_HORA_LLEGADA',
        ),
        migrations.AlterField(
            model_name='bus',
            name='BUS_VIGENCIA',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='CFR_VIGENCIA',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pasajeros',
            name='PSR_VIGENCIA',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='PRS_VIGENCIA',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservapasajero',
            name='RSV_VIGENCIA',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='TYO_VIGENCIA',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PromedioTrayectosReservas',
        ),
    ]
